services:
  worker:
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=crm_arbitrage.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
  beat:
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=crm_arbitrage.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
