
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crm
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  web:
    environment: {}
    env_file: .env
    build: .
    command: ["/app/start.sh"]
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  caddy:
    healthcheck:
      test: ["CMD","wget","-q","-O","-","http://127.0.0.1"]
      interval: 30s
      timeout: 5s
      retries: 5
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./staticfiles:/srv/staticfiles:ro
      - ./media:/srv/media:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
volumes:
  dbdata:
  caddy_data:
  caddy_config:
