# Generated by Django 4.2.1 on 2025-08-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeitaroEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subid", models.CharField(db_index=True, max_length=255)),
                ("status", models.CharField(db_index=True, max_length=64)),
                (
                    "payout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("raw", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subid", "status", "created_at"],
                        name="api_orders__subid_c46088_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="keitaroevent",
            constraint=models.UniqueConstraint(
                fields=("subid", "status"), name="uniq_subid_status"
            ),
        ),
    ]
