# Generated by Django 4.2.1 on 2025-08-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_orders", "0002_keitaroevent_keitaroevent_uniq_subid_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="keitaro_subid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
