# Generated by Django 4.2.1 on 2025-08-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_orders", "0003_order_keitaro_subid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payout",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
