# Generated by Django 4.2.1 on 2025-08-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_orders", "0004_order_payout_order_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="keitaroevent",
            name="uniq_subid_status",
        ),
        migrations.RemoveIndex(
            model_name="keitaroevent",
            name="api_orders__subid_c46088_idx",
        ),
        migrations.AddIndex(
            model_name="keitaroevent",
            index=models.Index(fields=["subid"], name="api_orders__subid_c1a23e_idx"),
        ),
    ]
